apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-catalog
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  minio.properties: |
    connector.name=hive
    hive.metastore=file
    hive.metastore.catalog.dir=/data/trino/metadata
