apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-archiver-s3-ca
  labels:
    {{- include "audit-archiver.labels" . | nindent 4 }}
data:
  s3-lb.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGBTCCA+2gAwIBAgIUG9jL0fe6412wEIBSool/Xv1oWGkwDQYJKoZIhvcNAQEL
    BQAwgYoxCzAJBgNVBAYTAlVBMQ0wCwYDVQQIDARLeWl2MQ0wCwYDVQQHDARLeWl2
    MQwwCgYDVQQKDANOQ1IxEDAOBgNVBAsMB0lUIERlcHQxGDAWBgNVBAMMD3MzLmty
    cnQtbmNyLmxvYzEjMCEGCSqGSIb3DQEJARYUbS5kdWJjaGFrQHVzcy5nb3YudWEw
    HhcNMjUwNTI4MDUzOTE4WhcNMzUwNTI2MDUzOTE4WjBeMQswCQYDVQQGEwJVQTEN
    MAsGA1UECAwES3lpdjENMAsGA1UEBwwES3lpdjEMMAoGA1UECgwDTkNSMSMwIQYJ
    KoZIhvcNAQkBFhRtLmR1YmNoYWtAdXNzLmdvdi51YTCCAiIwDQYJKoZIhvcNAQEB
    BQADggIPADCCAgoCggIBAKBcxWAMpGMvGS/9qVhk6jrQQ0V/9cP8ZqmJb3DTcN+j
    kaRsVBluO9p27QS/pFthONQWa9IISyW8Njp5nLfIdkgIDe9QvBrap4Gd5PUSelEp
    1FqJEpA56sJ12FxuKI9EuhYrJZn3d2KE3fiY20sz/2wD6fXt5hxXY7jbEwQugK2R
    2z7pCwbZBHaSI7Sua/AeSRot/o5nNbsDKfVRXIAHHc2m0xRLyWdSkQtOMQieitL1
    HsK4ZHJ8X4DlgQtCUKE90Z9FxkBmo3Vl4djvVfk7vc8mC6tJGy/n5M/wWmGeVdfn
    roYzjjxo2Qd3CnRmJpZOc8c/FPLywx3+CFThATWEe3h9vXPOS3G3bNTr+DVOIpRi
    z4Hku+A8PQtADVvjEQjcRpruSC1Gs2rdWXtXNyQs+O5ChGvhlFCuuDUKwn9uzkWQ
    DTgPq3AjR9cQFJmTxLQZ5Gf6MiDKJWlq1liBYpC4E59228JaiaKktvRvw8POy1af
    6adETV2BhJAc8LBqIVWeOTj7yraBk3dT4YRN27UQPf48+a0q4U1GbCdq7cHSjGcI
    R6+xXd/KqklkYbeJpvtfTsKu6u0SgPGTQIq5JtkJJi7DestBiAZATowKy9p48bYp
    Hb59oSoWOto+zcadgQIQS3tCJ88gjLFKXbHfe7urerojXdKNW9Uxpsd5MfiVLqqP
    AgMBAAGjgY0wgYowHwYDVR0jBBgwFoAUU27kNFiKBEcu7kfZGEYeyO1xuLQwCQYD
    VR0TBAIwADA9BgNVHREENjA0ghJzMy5rcnJ0Lm5jci5nb3YudWGCDXMzLm5jci5n
    b3YudWGCD3MzLmtycnQtbmNyLmxvYzAdBgNVHQ4EFgQUX9bRHN2/NH5LlZgc3Ap6
    73ZwDuswDQYJKoZIhvcNAQELBQADggIBAEsyPejAl/ABEkcXIgh4XCMRXyFLHwRT
    /1F5TVA3tx7SH5Rs1ZWmbl99BNq8Oxb/vx2jRMy1Vhs92xu2+YEjgZgf9gozxVMX
    5AnZsD2x1kGUGSxsVfxeXFG1W8YixLwps6D7s6pOuU4Hib368Er9HjkTsi1svQx+
    YyrCC+VBspYFO6B1xTErml7hIBrSdjYsv/NbSIv3Dv0URs9f10NgFKrbOYb0DOwc
    8e6HKvQm5OBcA3pwr6NsIuvgLLTLQmWuzvjL2Papju7dJlNif3nTauIFFEkmTuUu
    qaOBbpEzlETK1IUXpwupYEbyass/sliqqFX4Ii+aU1kH6uOW+CVoupnnBez4dvpE
    JSfqhJjCf0LJEn5dDTngeZDHt+MY3+0dxgFF3WVxQ3PuKhCUa9Cu436tnmLe14x/
    2YBc4YH9bkTlfNjSwgIp7OxZi+flK3MCqqt92OHbuwNs2smM9yBZiytsfYbOZaF9
    l2RBWiUtr2OsoKn8h6ualOMUtww9D8cjf24fJ32GzB6AtERssR8MmHjrT9zFn3ns
    psTiyHtm6qeXwMHKN6UGVJ1B/EG/cMUmSiDsuLkIjyd6WcqRVSB+nI5XM/x/v7TL
    /scEFesz/O9mSU9kURfwS+xBn0yz3b36WV7wp8to8dLMPE2RNlz1+/tCyBkF87Db
    uOP7x1oT7Hlj
    -----END CERTIFICATE-----
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCgXMVgDKRjLxkv
    /alYZOo60ENFf/XD/GapiW9w03Dfo5GkbFQZbjvadu0Ev6RbYTjUFmvSCEslvDY6
    eZy3yHZICA3vULwa2qeBneT1EnpRKdRaiRKQOerCddhcbiiPRLoWKyWZ93dihN34
    mNtLM/9sA+n17eYcV2O42xMELoCtkds+6QsG2QR2kiO0rmvwHkkaLf6OZzW7Ayn1
    UVyABx3NptMUS8lnUpELTjEInorS9R7CuGRyfF+A5YELQlChPdGfRcZAZqN1ZeHY
    71X5O73PJgurSRsv5+TP8FphnlXX566GM448aNkHdwp0ZiaWTnPHPxTy8sMd/ghU
    4QE1hHt4fb1zzktxt2zU6/g1TiKUYs+B5LvgPD0LQA1b4xEI3Eaa7kgtRrNq3Vl7
    VzckLPjuQoRr4ZRQrrg1CsJ/bs5FkA04D6twI0fXEBSZk8S0GeRn+jIgyiVpatZY
    gWKQuBOfdtvCWomipLb0b8PDzstWn+mnRE1dgYSQHPCwaiFVnjk4+8q2gZN3U+GE
    Tdu1ED3+PPmtKuFNRmwnau3B0oxnCEevsV3fyqpJZGG3iab7X07CrurtEoDxk0CK
    uSbZCSYuw3rLQYgGQE6MCsvaePG2KR2+faEqFjraPs3GnYECEEt7QifPIIyxSl2x
    33u7q3q6I13SjVvVMabHeTH4lS6qjwIDAQABAoICAEKYlE1Boskf551jAf9YFV/s
    WmuT6uwDt1zD2xhnbtIpOxQl+rz+5vNgfSkCL07VrsSBNTCpyg93PKwHEhrOsLRU
    R/kxNZUPZg3xlQJjtJFdRjd9Ak0MCF7OktY71zM8Tu1i6MAqoZUz6XzSegueof3p
    GDHOJMhzUFIWBK0xZLXwQzU6kZ475Nsa8KIZ53B2G1S4ciUQXqN1+mhK7BetHObp
    V3Jv0MnMY7jmtX1HXg6ixi4GZoyW8xBz/yW+Wf7ETfgPgXgAR/S6pVKyfik9cqOC
    wMjW2OgJrR/fyKEOoMbDi9pmsbSLtEmh2aEiRPcZyIIfw+LrBzW+6BXbxWVEygNE
    +J287nFZ1+mxsr+DJxWC5R4/g+LS0jxHAS33aKBbomxkBfxo7g+TUIuClWPnuAzW
    MIlTcPjHQuWB9AkiD2rY7ErdCA9sqemEsFXuL9w4wTtIcMYAn3BtvcNLUu5TsEab
    MoNOs5XCrRrpemWHxt1C9OUHj64hD7e5Xr7nZKE7iHC2PcPxhDws6j+l04HYpCIU
    N+A1jFfWWhW36awd4u1bEgwJddOy7fkncBEuqiTeyD6s58/SUNMLGD0op+U+hIH+
    LqZiNqHpRvcm9oN4UGs1MS80Zbil9L/rtNlf5s8AtK/LEFx0N9vZlO18tcq4pBgM
    LUp3GFeb6xrCbJt8sGhNAoIBAQDBbwsvHqdZt/NT6yLSRC6Mr7ElryvWsLKANRYa
    5K6dH1YvX/Sae8gVgqxJ0J7i6ITg0mVfhHMfPyVc71fFkYuv86+VUmjN4PXSgcM4
    /IZ7nep72p5PswHGW8g+BxS3GjaHFXhyJvzw26aCL/MF2dwjqtMOYK315d4+31q7
    Jbb2zkwpGZspClCQPtG2cPHXqOX+b4BT7i5Pe2ji7FN7AT7TKtyvsIQ5367AjYOY
    sC6lv6mHtHOTBGXLdRh+wf7GJew82bs3p5ExYvLLH4O1KLfZaD+bF33H8cKmMJbi
    cOKYUYdnsccQs9JXWWxvnGgPG6KEuxyFuwCEIG5QGMj4F209AoIBAQDUO07GAsj7
    DHOHJOtWNyNBfkPXnydhDAAFEHz4nROxsDYLaGJe3eu7AN6gqHA8zoMkfv9WDYys
    8MA1aHYQe3q+UQpPuGDW7MJfo5VspC1n0cUjSmhXAC6QmOXR3wM5ZA2TaSBYVlb9
    fkXgK739cIHFon2wfjDixe8m3IpmAqd/tCO5dwlqTVdYV2H55G7bT+bThdIiDnv4
    SnkC2FS6jSTn7Wl4cuIni6AAk0WQ6ASLuOAre7cVPS71H+L/kpmShuEYnVK4K8Bo
    B560dQ9l3xLsd3ayODTujTZGQIRm1a8ZWrZywMueKZ8LilXMK+DiwQf0vrAjUk1o
    JzHmPcpeZUu7AoIBAQCdAlGFsdANFy8/ksD1A7r1Hzcfa4yd+1coke6bbbv+dY0z
    byPQsWC7dRH76IbPkAUrqBv46D25wzvEr9IC4B0OeTKwde/0DQH8GLAp9XADry7B
    0bZm4tox9BYZow3Bgll4VIkrv1HY/7GsQtd0jF4P5XzjUr5htnArgIjZF8fnlZRk
    WBCFw4WZUCRRfmQPtVzapg74EYEtqvJ8H2+zjFM+fLAdO55Yi6QBT9zdd0Sl7Wji
    airVzuABwc5cNYNjuyyCSAmbJzzHZZXGIpJ53c89fU0DypGiVi61TwNqUk7bbHII
    TVlTyWKW3FMUVVRxzvCf5HFGa4ADv39LLJMULY/RAoIBAG+tfbgogwXH+Yrl3IiT
    nxO5k42FDD2/CMuhb4GLdm+MIAREu27cLE1NGdlEiTsWGGA+C7KGkr32Oc5g16+4
    qlA3aMumZB70mxukgt6WTeZRtgDqCJmvWNFyA406YwHyKkqliQWy+TePGMnreqBA
    calD5gvXe3X5Xez/JDylrOpAKoRPpT6w0AOGh+HtWIBDPV2VD4woPwfaeG8M0xkP
    aJo6jcN6AJN6n4lt9a9Yx/uWHzACe8bLWUhXrSV7SSCXpR9EueB79VVInTSsXJvo
    lJamDmmdtgzJdgPls0ZBr1ASMeuUlBD4Kd7yvk8fz8jCdqNNLHaJun3SEinr3e9q
    Mj0CggEAfThBQgTYfAWZdzCHYdpLdT3DiGOqf2qRKAA81csE0V3+5IrYHAavDGT4
    FeSu7uwH6mJXuQ40xb7SgXjq+wo5UdYy21++rni7woKDYy8EbWCDw9S/2ygLd+rF
    tV9C8JpJlM1zfi649hkedNSz5tjeb6NHUhQ5Iipxv56UFiYVQV+j+71OLsQFZqrR
    T1TxcVS+u1CxrK+6Kr+QMNro0cUMCIFWzrRB6DYjfk5ha/c5fQ2I/+7qiwFyqbdc
    Ms8pu4QdG32oSjn6W6z/6h4L5zqp5f7XJnjsK/KnxtNNjuZSSL1dhPtWfW3hU5Z7
    NxOawncwOoA1pDSdki+YLG+2KDCwMw==
    -----END PRIVATE KEY-----
