apiVersion: v1
kind: Pod
metadata:
  name: s3cli-debug-client
spec:
  containers:
    - name: awscli
      image: amazon/aws-cli:latest
      command: ["sleep", "3600"]
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "some_access_key"
        - name: AWS_SECRET_ACCESS_KEY
          value: "some_secret_key"
        - name: AWS_DEFAULT_REGION
          value: "some_region"
        - name: AWS_ENDPOINT_URL
          value: "https://some_s3_endpoint"
  restartPolicy: Never
