plugins {
    id 'groovy'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.0' // Пакує все в один збираний Fat JAR
}

group = 'diia.engine'
version = '1.0.0'

repositories {
    mavenCentral()
}

application {
    mainClass = 'diia.engine.audit.ArchiverJob'
}

dependencies {
    implementation 'org.apache.groovy:groovy:4.0.18'

    // Postgres & Connection
    implementation 'org.postgresql:postgresql:42.7.2'

    // AWS S3 SDK v2
    implementation 'software.amazon.awssdk:s3:2.25.15'

    // Apache Parquet + Avro (Стандарт для запису Parquet у світі JVM)
    implementation('org.apache.parquet:parquet-avro:1.13.1') {
        exclude group: 'org.apache.hadoop', module: 'hadoop-client'
    }
    implementation 'org.apache.hadoop:hadoop-common:3.3.6'
    implementation 'org.apache.hadoop:hadoop-mapreduce-client-core:3.3.6'
    implementation 'org.apache.avro:avro:1.11.3'

    // Логування
    implementation 'org.slf4j:slf4j-api:2.0.12'
    implementation 'ch.qos.logback:logback-classic:1.5.0'

    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")

    // Testing
    testImplementation platform("org.spockframework:spock-bom:2.3-groovy-4.0")
    testImplementation "org.spockframework:spock-core"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    
    // Потрібно для Mocking/Spying статичних методів та класів
    testImplementation "net.bytebuddy:byte-buddy:1.14.12" 
}

tasks.named('shadowJar') {
    mergeServiceFiles()
    archiveBaseName.set('audit-archiver')
    archiveClassifier.set('')
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
    }
}