# =====================================================
# Audit Archiver - Helm Values
# =====================================================

nameOverride: "audit-archiver-cronjob"

image:
  repository: harbor.diia.gov.ua/platform/audit-archiver
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
  # - name: harbor-pull-secret

schedule: "0 3 * * *"
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 5
failedJobsHistoryLimit: 3
backoffLimit: 2
ttlSecondsAfterFinished: 86400


retentionHours: 48
archiveTableName: ""

# =====================================================
# Database
# =====================================================
db:
  name: "audit"
  schema: "public"
  existingSecret: "analytical-pguser-postgres"
  hostKey: "host"
  portKey: "port"
  userKey: "user"
  passwordKey: "password"

# =====================================================
# S3
# =====================================================
s3:
  endpoint: "http://s3.krrt-ncr.loc:9000"
  region: "eu-central-1"
  bucket: "s3-aikom-test"
  existingSecret: "s3-test"
  accessKey: "AccessKey"
  secretKey: "SecretAccessKey"

resources:
  requests:
    memory: "768Mi"
    cpu: "500m"
    ephemeral-storage: "2Gi"
  limits:
    memory: "1536Mi"
    cpu: "1500m"
    ephemeral-storage: "10Gi"

tmpStorage:
  sizeLimit: "8Gi"

extraEnv: []

serviceAccount:
  create: false
  name: ""
