DO $redash_migration_5da377a970624ae4caa844c17c4b69a0$
-- Generated Redash migration script. Save this text locally from pgAdmin before executing it on Viewer.
    DECLARE
        v_datasource_id integer;
        v_user_id integer := 1;
        v_match_count integer;
        v_target_org_id integer := 1;
        v_dashboard_128 integer;
        v_dashboard_129 integer;
        v_dashboard_130 integer;
        v_dashboard_131 integer;
        v_dashboard_132 integer;
        v_query_266 integer;
        v_query_267 integer;
        v_query_268 integer;
        v_visualization_268 integer;
        v_widget_268 integer;
        v_query_269 integer;
        v_visualization_269 integer;
        v_widget_269 integer;
        v_query_270 integer;
        v_visualization_270 integer;
        v_widget_270 integer;
        v_visualization_271 integer;
        v_widget_271 integer;
        v_visualization_272 integer;
        v_widget_272 integer;
        v_visualization_273 integer;
        v_widget_273 integer;
        v_visualization_274 integer;
        v_widget_274 integer;
        v_visualization_275 integer;
        v_widget_275 integer;
    BEGIN
        -- Configuration
        -- target_org_id: 1
        -- target_user_id: 1
        -- Admin scope: 5 configured-datasource queries; 5/149 dashboards selected (mixed-datasource dashboards skipped).
-- Find datasource
        SELECT count(*), min(id) INTO v_match_count, v_datasource_id FROM data_sources WHERE org_id = v_target_org_id AND name = 's3-audit' AND type = 'trino';
        IF v_match_count = 0 THEN RAISE EXCEPTION 'Datasource not found in Viewer: org_id=%, name=%, type=%', v_target_org_id, 's3-audit', 'trino'; END IF;
        IF v_match_count > 1 THEN RAISE EXCEPTION 'Datasource is ambiguous in Viewer: org_id=%, name=%, type=%', v_target_org_id, 's3-audit', 'trino'; END IF;
-- Find user
        SELECT count(*) INTO v_match_count FROM users WHERE id = v_user_id AND org_id = v_target_org_id;
        IF v_match_count = 0 THEN RAISE EXCEPTION 'User not found in Viewer: id=%, org_id=%', v_user_id, v_target_org_id; END IF;
-- Queries (upsert by organization, datasource, and name)
        SELECT count(*), min(id) INTO v_match_count, v_query_266 FROM queries WHERE org_id = v_target_org_id AND data_source_id = v_datasource_id AND name = '01. Статистика по подіях (розподіл по часу)'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer queries match name % for org_id=% and datasource_id=%', '01. Статистика по подіях (розподіл по часу)', v_target_org_id, v_datasource_id; END IF; IF v_match_count = 0 THEN INSERT INTO queries (updated_at, created_at, version, org_id, data_source_id, latest_query_data_id, name, description, query, query_hash, api_key, user_id, last_modified_by_id, is_archived, is_draft, schedule, schedule_failures, options, search_vector, tags) VALUES ('2026-07-24 06:47:16.779342+00'::timestamptz, '2026-07-22 06:18:54.272446+00'::timestamptz, 1, v_target_org_id, v_datasource_id, NULL, '01. Статистика по подіях (розподіл по часу)', NULL, 'SELECT
    CAST("timestamp" AS DATE) AS event_date,
    COUNT(*) AS events_count,
    MIN("timestamp") AS min_time,
    MAX("timestamp") AS max_time
FROM audit.events
WHERE
    "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
GROUP BY 1
ORDER BY 1 DESC', '17143c769d141e67c99ed1985232e0de', 'XXcqc3oDmsK3YRMJwzeRrmhI1THCxgg5Vo7TqeY7', v_user_id, v_user_id, 'false'::boolean, 'false'::boolean, NULL, 0, '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "date-range", "global": false, "locals": [], "value": "d_this_year"}]}', '''01'':2A ''1'':52,55 ''266'':1B ''and'':43 ''as'':12,14,18,23,28,41,48 ''audit'':32 ''between'':36 ''by'':51,54 ''cast'':10,37,44 ''count'':17,20 ''date'':13,16,39,46 ''desc'':56 ''end'':47 ''event'':15,38,45 ''events'':19,33 ''from'':31 ''group'':50 ''max'':26,29 ''min'':21,24 ''order'':53 ''select'':9 ''start'':40 ''time'':25,30 ''timestamp'':11,22,27,35,42,49 ''where'':34 ''по'':4A,7A ''подіях'':5A ''розподіл'':6A ''статистика'':3A ''часу'':8A'::tsvector, '{audit}'::varchar[]) RETURNING id INTO v_query_266; ELSE UPDATE queries SET updated_at = '2026-07-24 06:47:16.779342+00'::timestamptz, version = 1, latest_query_data_id = NULL, description = NULL, query = 'SELECT
    CAST("timestamp" AS DATE) AS event_date,
    COUNT(*) AS events_count,
    MIN("timestamp") AS min_time,
    MAX("timestamp") AS max_time
FROM audit.events
WHERE
    "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
GROUP BY 1
ORDER BY 1 DESC', query_hash = '17143c769d141e67c99ed1985232e0de', api_key = 'XXcqc3oDmsK3YRMJwzeRrmhI1THCxgg5Vo7TqeY7', user_id = v_user_id, last_modified_by_id = v_user_id, is_archived = 'false'::boolean, is_draft = 'false'::boolean, schedule = NULL, schedule_failures = 0, options = '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "date-range", "global": false, "locals": [], "value": "d_this_year"}]}', search_vector = '''01'':2A ''1'':52,55 ''266'':1B ''and'':43 ''as'':12,14,18,23,28,41,48 ''audit'':32 ''between'':36 ''by'':51,54 ''cast'':10,37,44 ''count'':17,20 ''date'':13,16,39,46 ''desc'':56 ''end'':47 ''event'':15,38,45 ''events'':19,33 ''from'':31 ''group'':50 ''max'':26,29 ''min'':21,24 ''order'':53 ''select'':9 ''start'':40 ''time'':25,30 ''timestamp'':11,22,27,35,42,49 ''where'':34 ''по'':4A,7A ''подіях'':5A ''розподіл'':6A ''статистика'':3A ''часу'':8A'::tsvector, tags = '{audit}'::varchar[] WHERE id = v_query_266; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_query_267 FROM queries WHERE org_id = v_target_org_id AND data_source_id = v_datasource_id AND name = '02. Всі події (за день)'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer queries match name % for org_id=% and datasource_id=%', '02. Всі події (за день)', v_target_org_id, v_datasource_id; END IF; IF v_match_count = 0 THEN INSERT INTO queries (updated_at, created_at, version, org_id, data_source_id, latest_query_data_id, name, description, query, query_hash, api_key, user_id, last_modified_by_id, is_archived, is_draft, schedule, schedule_failures, options, search_vector, tags) VALUES ('2026-07-23 09:03:32.817141+00'::timestamptz, '2026-07-22 06:20:08.642051+00'::timestamptz, 1, v_target_org_id, v_datasource_id, NULL, '02. Всі події (за день)', NULL, 'SELECT
    id,
    request_id,
    application_name AS "application_name::multi-filter",
    name,
    type AS "type::multi-filter",
    "timestamp",
    user_keycloak_id,
    user_name,
    user_drfo,
    source_system,
    source_application,
    source_business_process,
    source_business_process_definition_id,
    source_business_process_instance_id,
    source_business_activity,
    source_business_activity_id,
    context,
    received
FROM audit.events
WHERE
    "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
ORDER BY "timestamp" ASC
LIMIT {{ limit }}', '220ef6d6e293dee3c904a79e44e49c33', 'dTaPwdRO7GDT0gBL4JADEdnxd0sVkIAnetZLpC0I', v_user_id, v_user_id, 'false'::boolean, 'false'::boolean, NULL, 0, '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "datetime-range-with-seconds", "global": false, "locals": [], "value": "d_yesterday"}, {"title": "limit", "name": "limit", "type": "text", "global": false, "locals": [], "value": "1000"}]}', '''02'':2A ''267'':1B ''activity'':51,54 ''and'':70 ''application'':11,14,35 ''as'':13,20,68,75 ''asc'':80 ''audit'':59 ''between'':63 ''business'':37,40,45,50,53 ''by'':78 ''cast'':64,71 ''context'':56 ''date'':66,73 ''definition'':42 ''drfo'':31 ''end'':74 ''event'':65,72 ''events'':60 ''filter'':17,23 ''from'':58 ''id'':8,10,27,43,48,55 ''instance'':47 ''keycloak'':26 ''limit'':81,82 ''multi'':16,22 ''name'':12,15,18,29 ''order'':77 ''process'':38,41,46 ''received'':57 ''request'':9 ''select'':7 ''source'':32,34,36,39,44,49,52 ''start'':67 ''system'':33 ''timestamp'':24,62,69,76,79 ''type'':19,21 ''user'':25,28,30 ''where'':61 ''всі'':3A ''день'':6A ''за'':5A ''події'':4A'::tsvector, '{audit}'::varchar[]) RETURNING id INTO v_query_267; ELSE UPDATE queries SET updated_at = '2026-07-23 09:03:32.817141+00'::timestamptz, version = 1, latest_query_data_id = NULL, description = NULL, query = 'SELECT
    id,
    request_id,
    application_name AS "application_name::multi-filter",
    name,
    type AS "type::multi-filter",
    "timestamp",
    user_keycloak_id,
    user_name,
    user_drfo,
    source_system,
    source_application,
    source_business_process,
    source_business_process_definition_id,
    source_business_process_instance_id,
    source_business_activity,
    source_business_activity_id,
    context,
    received
FROM audit.events
WHERE
    "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
ORDER BY "timestamp" ASC
LIMIT {{ limit }}', query_hash = '220ef6d6e293dee3c904a79e44e49c33', api_key = 'dTaPwdRO7GDT0gBL4JADEdnxd0sVkIAnetZLpC0I', user_id = v_user_id, last_modified_by_id = v_user_id, is_archived = 'false'::boolean, is_draft = 'false'::boolean, schedule = NULL, schedule_failures = 0, options = '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "datetime-range-with-seconds", "global": false, "locals": [], "value": "d_yesterday"}, {"title": "limit", "name": "limit", "type": "text", "global": false, "locals": [], "value": "1000"}]}', search_vector = '''02'':2A ''267'':1B ''activity'':51,54 ''and'':70 ''application'':11,14,35 ''as'':13,20,68,75 ''asc'':80 ''audit'':59 ''between'':63 ''business'':37,40,45,50,53 ''by'':78 ''cast'':64,71 ''context'':56 ''date'':66,73 ''definition'':42 ''drfo'':31 ''end'':74 ''event'':65,72 ''events'':60 ''filter'':17,23 ''from'':58 ''id'':8,10,27,43,48,55 ''instance'':47 ''keycloak'':26 ''limit'':81,82 ''multi'':16,22 ''name'':12,15,18,29 ''order'':77 ''process'':38,41,46 ''received'':57 ''request'':9 ''select'':7 ''source'':32,34,36,39,44,49,52 ''start'':67 ''system'':33 ''timestamp'':24,62,69,76,79 ''type'':19,21 ''user'':25,28,30 ''where'':61 ''всі'':3A ''день'':6A ''за'':5A ''події'':4A'::tsvector, tags = '{audit}'::varchar[] WHERE id = v_query_267; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_query_268 FROM queries WHERE org_id = v_target_org_id AND data_source_id = v_datasource_id AND name = '03. Пошук по request_id'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer queries match name % for org_id=% and datasource_id=%', '03. Пошук по request_id', v_target_org_id, v_datasource_id; END IF; IF v_match_count = 0 THEN INSERT INTO queries (updated_at, created_at, version, org_id, data_source_id, latest_query_data_id, name, description, query, query_hash, api_key, user_id, last_modified_by_id, is_archived, is_draft, schedule, schedule_failures, options, search_vector, tags) VALUES ('2026-07-22 10:13:26.7066+00'::timestamptz, '2026-07-22 06:20:44.663865+00'::timestamptz, 1, v_target_org_id, v_datasource_id, NULL, '03. Пошук по request_id', NULL, 'SELECT *
FROM audit.events
WHERE request_id = ''{{ request_id }}''
    AND "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
ORDER BY "timestamp" ASC', 'b240f598af0a963f8a4ba0ea1381d75c', 'Td7itn6iRaZ2LGTG2JPv4InrRCgRH4DWo4Yl84y5', v_user_id, v_user_id, 'false'::boolean, 'false'::boolean, NULL, 0, '{"apply_auto_limit": false, "parameters": [{"title": "request_id", "name": "request_id", "type": "text", "global": false, "locals": [], "value": null}, {"title": "event_date", "name": "event_date", "type": "date-range", "global": false, "locals": [], "value": null}]}', '''03'':2A ''268'':1B ''and'':16,25 ''as'':23,30 ''asc'':35 ''audit'':9 ''between'':18 ''by'':33 ''cast'':19,26 ''date'':21,28 ''end'':29 ''event'':20,27 ''events'':10 ''from'':8 ''id'':6A,13,15 ''order'':32 ''request'':5A,12,14 ''select'':7 ''start'':22 ''timestamp'':17,24,31,34 ''where'':11 ''по'':4A ''пошук'':3A'::tsvector, '{audit}'::varchar[]) RETURNING id INTO v_query_268; ELSE UPDATE queries SET updated_at = '2026-07-22 10:13:26.7066+00'::timestamptz, version = 1, latest_query_data_id = NULL, description = NULL, query = 'SELECT *
FROM audit.events
WHERE request_id = ''{{ request_id }}''
    AND "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
ORDER BY "timestamp" ASC', query_hash = 'b240f598af0a963f8a4ba0ea1381d75c', api_key = 'Td7itn6iRaZ2LGTG2JPv4InrRCgRH4DWo4Yl84y5', user_id = v_user_id, last_modified_by_id = v_user_id, is_archived = 'false'::boolean, is_draft = 'false'::boolean, schedule = NULL, schedule_failures = 0, options = '{"apply_auto_limit": false, "parameters": [{"title": "request_id", "name": "request_id", "type": "text", "global": false, "locals": [], "value": null}, {"title": "event_date", "name": "event_date", "type": "date-range", "global": false, "locals": [], "value": null}]}', search_vector = '''03'':2A ''268'':1B ''and'':16,25 ''as'':23,30 ''asc'':35 ''audit'':9 ''between'':18 ''by'':33 ''cast'':19,26 ''date'':21,28 ''end'':29 ''event'':20,27 ''events'':10 ''from'':8 ''id'':6A,13,15 ''order'':32 ''request'':5A,12,14 ''select'':7 ''start'':22 ''timestamp'':17,24,31,34 ''where'':11 ''по'':4A ''пошук'':3A'::tsvector, tags = '{audit}'::varchar[] WHERE id = v_query_268; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_query_269 FROM queries WHERE org_id = v_target_org_id AND data_source_id = v_datasource_id AND name = '04. Денна активність сервісів'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer queries match name % for org_id=% and datasource_id=%', '04. Денна активність сервісів', v_target_org_id, v_datasource_id; END IF; IF v_match_count = 0 THEN INSERT INTO queries (updated_at, created_at, version, org_id, data_source_id, latest_query_data_id, name, description, query, query_hash, api_key, user_id, last_modified_by_id, is_archived, is_draft, schedule, schedule_failures, options, search_vector, tags) VALUES ('2026-07-23 09:02:59.587589+00'::timestamptz, '2026-07-22 06:21:48.141712+00'::timestamptz, 1, v_target_org_id, v_datasource_id, NULL, '04. Денна активність сервісів', NULL, 'SELECT
    date_trunc(''day'', "timestamp") AS event_date,
    application_name,
    count(*) AS total_events
FROM minio.audit.events
WHERE "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
GROUP BY 1, 2
ORDER BY 1 DESC, 3 DESC', 'f2f0f5c298d6337f82abba00155e4b76', '5gM4fiTiG0h6VU3dD0BNivSWruNqH2CXeD3SxM1S', v_user_id, v_user_id, 'false'::boolean, 'false'::boolean, NULL, 0, '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "datetime-range", "global": false, "locals": [], "value": "d_yesterday"}]}', '''04'':2A ''1'':42,46 ''2'':43 ''269'':1B ''3'':48 ''and'':33 ''application'':14 ''as'':11,17,31,38 ''audit'':22 ''between'':26 ''by'':41,45 ''cast'':27,34 ''count'':16 ''date'':7,13,29,36 ''day'':9 ''desc'':47,49 ''end'':37 ''event'':12,28,35 ''events'':19,23 ''from'':20 ''group'':40 ''minio'':21 ''name'':15 ''order'':44 ''select'':6 ''start'':30 ''timestamp'':10,25,32,39 ''total'':18 ''trunc'':8 ''where'':24 ''активність'':4A ''денна'':3A ''сервісів'':5A'::tsvector, '{audit}'::varchar[]) RETURNING id INTO v_query_269; ELSE UPDATE queries SET updated_at = '2026-07-23 09:02:59.587589+00'::timestamptz, version = 1, latest_query_data_id = NULL, description = NULL, query = 'SELECT
    date_trunc(''day'', "timestamp") AS event_date,
    application_name,
    count(*) AS total_events
FROM minio.audit.events
WHERE "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
GROUP BY 1, 2
ORDER BY 1 DESC, 3 DESC', query_hash = 'f2f0f5c298d6337f82abba00155e4b76', api_key = '5gM4fiTiG0h6VU3dD0BNivSWruNqH2CXeD3SxM1S', user_id = v_user_id, last_modified_by_id = v_user_id, is_archived = 'false'::boolean, is_draft = 'false'::boolean, schedule = NULL, schedule_failures = 0, options = '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "datetime-range", "global": false, "locals": [], "value": "d_yesterday"}]}', search_vector = '''04'':2A ''1'':42,46 ''2'':43 ''269'':1B ''3'':48 ''and'':33 ''application'':14 ''as'':11,17,31,38 ''audit'':22 ''between'':26 ''by'':41,45 ''cast'':27,34 ''count'':16 ''date'':7,13,29,36 ''day'':9 ''desc'':47,49 ''end'':37 ''event'':12,28,35 ''events'':19,23 ''from'':20 ''group'':40 ''minio'':21 ''name'':15 ''order'':44 ''select'':6 ''start'':30 ''timestamp'':10,25,32,39 ''total'':18 ''trunc'':8 ''where'':24 ''активність'':4A ''денна'':3A ''сервісів'':5A'::tsvector, tags = '{audit}'::varchar[] WHERE id = v_query_269; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_query_270 FROM queries WHERE org_id = v_target_org_id AND data_source_id = v_datasource_id AND name = '05. Аналіз "шуму" (Що найбільше забиває базу)'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer queries match name % for org_id=% and datasource_id=%', '05. Аналіз "шуму" (Що найбільше забиває базу)', v_target_org_id, v_datasource_id; END IF; IF v_match_count = 0 THEN INSERT INTO queries (updated_at, created_at, version, org_id, data_source_id, latest_query_data_id, name, description, query, query_hash, api_key, user_id, last_modified_by_id, is_archived, is_draft, schedule, schedule_failures, options, search_vector, tags) VALUES ('2026-07-23 09:04:56.431114+00'::timestamptz, '2026-07-22 06:22:29.801157+00'::timestamptz, 1, v_target_org_id, v_datasource_id, NULL, '05. Аналіз "шуму" (Що найбільше забиває базу)', NULL, 'SELECT
    application_name,
    name AS event_name,
    type AS event_type,
    count(*) AS hits
FROM minio.audit.events
WHERE "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
GROUP BY 1, 2, 3
ORDER BY hits DESC
LIMIT 10', 'f4a554bc84ab8d9d93cfcf8cc58f91d1', '15v0oIXv1CG8zwMzyMo5Lh9D4ucxfKFABsixVZhO', v_user_id, v_user_id, 'false'::boolean, 'false'::boolean, NULL, 0, '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "datetime-range", "global": false, "locals": [], "value": "d_yesterday"}]}', '''05'':2A ''1'':45 ''10'':53 ''2'':46 ''270'':1B ''3'':47 ''and'':36 ''application'':10 ''as'':13,17,21,34,41 ''audit'':25 ''between'':29 ''by'':44,49 ''cast'':30,37 ''count'':20 ''date'':32,39 ''desc'':51 ''end'':40 ''event'':14,18,31,38 ''events'':26 ''from'':23 ''group'':43 ''hits'':22,50 ''limit'':52 ''minio'':24 ''name'':11,12,15 ''order'':48 ''select'':9 ''start'':33 ''timestamp'':28,35,42 ''type'':16,19 ''where'':27 ''аналіз'':3A ''базу'':8A ''забиває'':7A ''найбільше'':6A ''шуму'':4A ''що'':5A'::tsvector, '{audit}'::varchar[]) RETURNING id INTO v_query_270; ELSE UPDATE queries SET updated_at = '2026-07-23 09:04:56.431114+00'::timestamptz, version = 1, latest_query_data_id = NULL, description = NULL, query = 'SELECT
    application_name,
    name AS event_name,
    type AS event_type,
    count(*) AS hits
FROM minio.audit.events
WHERE "timestamp" BETWEEN cast(''{{ event_date.start }}'' as timestamp) AND cast(''{{ event_date.end }}'' as timestamp)
GROUP BY 1, 2, 3
ORDER BY hits DESC
LIMIT 10', query_hash = 'f4a554bc84ab8d9d93cfcf8cc58f91d1', api_key = '15v0oIXv1CG8zwMzyMo5Lh9D4ucxfKFABsixVZhO', user_id = v_user_id, last_modified_by_id = v_user_id, is_archived = 'false'::boolean, is_draft = 'false'::boolean, schedule = NULL, schedule_failures = 0, options = '{"apply_auto_limit": false, "parameters": [{"title": "event_date", "name": "event_date", "type": "datetime-range", "global": false, "locals": [], "value": "d_yesterday"}]}', search_vector = '''05'':2A ''1'':45 ''10'':53 ''2'':46 ''270'':1B ''3'':47 ''and'':36 ''application'':10 ''as'':13,17,21,34,41 ''audit'':25 ''between'':29 ''by'':44,49 ''cast'':30,37 ''count'':20 ''date'':32,39 ''desc'':51 ''end'':40 ''event'':14,18,31,38 ''events'':26 ''from'':23 ''group'':43 ''hits'':22,50 ''limit'':52 ''minio'':24 ''name'':11,12,15 ''order'':48 ''select'':9 ''start'':33 ''timestamp'':28,35,42 ''type'':16,19 ''where'':27 ''аналіз'':3A ''базу'':8A ''забиває'':7A ''найбільше'':6A ''шуму'':4A ''що'':5A'::tsvector, tags = '{audit}'::varchar[] WHERE id = v_query_270; END IF;
-- Visualizations (reuse identical records)
        SELECT count(*), min(id) INTO v_match_count, v_visualization_268 FROM visualizations WHERE query_id = v_query_266 AND type = 'TABLE' AND name IS NOT DISTINCT FROM 'Table' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_266; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 06:51:38.935676+00'::timestamptz, '2026-07-22 06:18:54.272446+00'::timestamptz, 'TABLE', v_query_266, 'Table', '', '{}') RETURNING id INTO v_visualization_268; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_269 FROM visualizations WHERE query_id = v_query_267 AND type = 'TABLE' AND name IS NOT DISTINCT FROM 'Table' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_267; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 08:54:37.207524+00'::timestamptz, '2026-07-22 06:20:08.642051+00'::timestamptz, 'TABLE', v_query_267, 'Table', '', '{}') RETURNING id INTO v_visualization_269; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_270 FROM visualizations WHERE query_id = v_query_268 AND type = 'TABLE' AND name IS NOT DISTINCT FROM 'Table' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_268; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 08:57:33.436025+00'::timestamptz, '2026-07-22 06:20:44.663865+00'::timestamptz, 'TABLE', v_query_268, 'Table', '', '{}') RETURNING id INTO v_visualization_270; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_271 FROM visualizations WHERE query_id = v_query_269 AND type = 'TABLE' AND name IS NOT DISTINCT FROM 'Table' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_269; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 09:01:10.520427+00'::timestamptz, '2026-07-22 06:21:48.141712+00'::timestamptz, 'TABLE', v_query_269, 'Table', '', '{}') RETURNING id INTO v_visualization_271; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_272 FROM visualizations WHERE query_id = v_query_270 AND type = 'TABLE' AND name IS NOT DISTINCT FROM 'Table' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_270; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 09:03:57.325763+00'::timestamptz, '2026-07-22 06:22:29.801157+00'::timestamptz, 'TABLE', v_query_270, 'Table', '', '{}') RETURNING id INTO v_visualization_272; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_273 FROM visualizations WHERE query_id = v_query_269 AND type = 'CHART' AND name IS NOT DISTINCT FROM 'Chart' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto", "traceorder": "normal"}, "xAxis": {"type": "-", "labels": {"enabled": true}}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "alignYAxesAtZero": false, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"application_name": "x", "total_events": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm", "swappedAxes": false}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_269; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 09:01:23.987102+00'::timestamptz, '2026-07-22 10:15:54.372256+00'::timestamptz, 'CHART', v_query_269, 'Chart', '', '{"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto", "traceorder": "normal"}, "xAxis": {"type": "-", "labels": {"enabled": true}}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "alignYAxesAtZero": false, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"application_name": "x", "total_events": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm", "swappedAxes": false}') RETURNING id INTO v_visualization_273; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_274 FROM visualizations WHERE query_id = v_query_266 AND type = 'CHART' AND name IS NOT DISTINCT FROM 'Chart' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto", "traceorder": "normal"}, "xAxis": {"type": "-", "labels": {"enabled": true}}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "alignYAxesAtZero": false, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"event_date": "x", "events_count": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm"}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_266; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 08:52:32.508341+00'::timestamptz, '2026-07-22 10:16:25.98359+00'::timestamptz, 'CHART', v_query_266, 'Chart', '', '{"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto", "traceorder": "normal"}, "xAxis": {"type": "-", "labels": {"enabled": true}}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "alignYAxesAtZero": false, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"event_date": "x", "events_count": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm"}') RETURNING id INTO v_visualization_274; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_visualization_275 FROM visualizations WHERE query_id = v_query_270 AND type = 'CHART' AND name IS NOT DISTINCT FROM 'Chart' AND description IS NOT DISTINCT FROM '' AND options IS NOT DISTINCT FROM '{"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto", "traceorder": "normal"}, "xAxis": {"type": "-", "labels": {"enabled": true}}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "alignYAxesAtZero": false, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"event_name": "x", "hits": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm", "swappedAxes": true}'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer visualizations have identical content for query %', v_query_270; END IF; IF v_match_count = 0 THEN INSERT INTO visualizations (updated_at, created_at, type, query_id, name, description, options) VALUES ('2026-07-23 09:04:05.228825+00'::timestamptz, '2026-07-22 11:00:51.763+00'::timestamptz, 'CHART', v_query_270, 'Chart', '', '{"globalSeriesType": "column", "sortX": true, "legend": {"enabled": true, "placement": "auto", "traceorder": "normal"}, "xAxis": {"type": "-", "labels": {"enabled": true}}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "alignYAxesAtZero": false, "error_y": {"type": "data", "visible": true}, "series": {"stacking": null, "error_y": {"type": "data", "visible": true}}, "seriesOptions": {}, "valuesOptions": {}, "columnMapping": {"event_name": "x", "hits": "y"}, "direction": {"type": "counterclockwise"}, "sizemode": "diameter", "coefficient": 1, "numberFormat": "0,0[.]00000", "percentFormat": "0[.]00%", "textFormat": "", "missingValuesAsZero": true, "showDataLabels": false, "dateTimeFormat": "DD/MM/YY HH:mm", "swappedAxes": true}') RETURNING id INTO v_visualization_275; END IF;
-- Dashboards (upsert by organization and name)
        SELECT count(*), min(id) INTO v_match_count, v_dashboard_128 FROM dashboards WHERE org_id = v_target_org_id AND name = '01. Статистика по подіях (розподіл по часу)'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer dashboards match name % for org_id=%', '01. Статистика по подіях (розподіл по часу)', v_target_org_id; END IF; IF v_match_count = 0 THEN INSERT INTO dashboards (updated_at, created_at, version, org_id, slug, name, user_id, layout, dashboard_filters_enabled, is_archived, is_draft, tags, options) VALUES ('2026-07-23 08:52:09.910115+00'::timestamptz, '2026-07-23 06:51:30.101975+00'::timestamptz, 3, v_target_org_id, '01-', '01. Статистика по подіях (розподіл по часу)', v_user_id, '[]', 'false'::boolean, 'false'::boolean, 'false'::boolean, '{audit}'::varchar[], '{}'::json) RETURNING id INTO v_dashboard_128; ELSE UPDATE dashboards SET updated_at = '2026-07-23 08:52:09.910115+00'::timestamptz, version = 3, slug = '01-', user_id = v_user_id, layout = '[]', dashboard_filters_enabled = 'false'::boolean, is_archived = 'false'::boolean, is_draft = 'false'::boolean, tags = '{audit}'::varchar[], options = '{}'::json WHERE id = v_dashboard_128; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_dashboard_129 FROM dashboards WHERE org_id = v_target_org_id AND name = '02. Всі події (за день)'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer dashboards match name % for org_id=%', '02. Всі події (за день)', v_target_org_id; END IF; IF v_match_count = 0 THEN INSERT INTO dashboards (updated_at, created_at, version, org_id, slug, name, user_id, layout, dashboard_filters_enabled, is_archived, is_draft, tags, options) VALUES ('2026-07-23 08:55:12.881891+00'::timestamptz, '2026-07-23 08:54:22.409528+00'::timestamptz, 5, v_target_org_id, '02-', '02. Всі події (за день)', v_user_id, '[]', 'false'::boolean, 'false'::boolean, 'false'::boolean, '{audit}'::varchar[], '{}'::json) RETURNING id INTO v_dashboard_129; ELSE UPDATE dashboards SET updated_at = '2026-07-23 08:55:12.881891+00'::timestamptz, version = 5, slug = '02-', user_id = v_user_id, layout = '[]', dashboard_filters_enabled = 'false'::boolean, is_archived = 'false'::boolean, is_draft = 'false'::boolean, tags = '{audit}'::varchar[], options = '{}'::json WHERE id = v_dashboard_129; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_dashboard_130 FROM dashboards WHERE org_id = v_target_org_id AND name = '03. Пошук по request_id'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer dashboards match name % for org_id=%', '03. Пошук по request_id', v_target_org_id; END IF; IF v_match_count = 0 THEN INSERT INTO dashboards (updated_at, created_at, version, org_id, slug, name, user_id, layout, dashboard_filters_enabled, is_archived, is_draft, tags, options) VALUES ('2026-07-23 08:57:44.737536+00'::timestamptz, '2026-07-23 08:57:21.08292+00'::timestamptz, 3, v_target_org_id, '03-request_id', '03. Пошук по request_id', v_user_id, '[]', 'false'::boolean, 'false'::boolean, 'false'::boolean, '{audit}'::varchar[], '{}'::json) RETURNING id INTO v_dashboard_130; ELSE UPDATE dashboards SET updated_at = '2026-07-23 08:57:44.737536+00'::timestamptz, version = 3, slug = '03-request_id', user_id = v_user_id, layout = '[]', dashboard_filters_enabled = 'false'::boolean, is_archived = 'false'::boolean, is_draft = 'false'::boolean, tags = '{audit}'::varchar[], options = '{}'::json WHERE id = v_dashboard_130; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_dashboard_131 FROM dashboards WHERE org_id = v_target_org_id AND name = '04. Денна активність сервісів'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer dashboards match name % for org_id=%', '04. Денна активність сервісів', v_target_org_id; END IF; IF v_match_count = 0 THEN INSERT INTO dashboards (updated_at, created_at, version, org_id, slug, name, user_id, layout, dashboard_filters_enabled, is_archived, is_draft, tags, options) VALUES ('2026-07-23 09:02:04.907459+00'::timestamptz, '2026-07-23 09:01:00.819085+00'::timestamptz, 3, v_target_org_id, '04-', '04. Денна активність сервісів', v_user_id, '[]', 'false'::boolean, 'false'::boolean, 'false'::boolean, '{audit}'::varchar[], '{}'::json) RETURNING id INTO v_dashboard_131; ELSE UPDATE dashboards SET updated_at = '2026-07-23 09:02:04.907459+00'::timestamptz, version = 3, slug = '04-', user_id = v_user_id, layout = '[]', dashboard_filters_enabled = 'false'::boolean, is_archived = 'false'::boolean, is_draft = 'false'::boolean, tags = '{audit}'::varchar[], options = '{}'::json WHERE id = v_dashboard_131; END IF;
        SELECT count(*), min(id) INTO v_match_count, v_dashboard_132 FROM dashboards WHERE org_id = v_target_org_id AND name = '05. Аналіз "шуму" (Що найбільше забиває базу)'; IF v_match_count > 1 THEN RAISE EXCEPTION 'Multiple Viewer dashboards match name % for org_id=%', '05. Аналіз "шуму" (Що найбільше забиває базу)', v_target_org_id; END IF; IF v_match_count = 0 THEN INSERT INTO dashboards (updated_at, created_at, version, org_id, slug, name, user_id, layout, dashboard_filters_enabled, is_archived, is_draft, tags, options) VALUES ('2026-07-23 09:05:34.803647+00'::timestamptz, '2026-07-23 09:03:52.603362+00'::timestamptz, 3, v_target_org_id, '05-', '05. Аналіз "шуму" (Що найбільше забиває базу)', v_user_id, '[]', 'false'::boolean, 'false'::boolean, 'false'::boolean, '{audit}'::varchar[], '{}'::json) RETURNING id INTO v_dashboard_132; ELSE UPDATE dashboards SET updated_at = '2026-07-23 09:05:34.803647+00'::timestamptz, version = 3, slug = '05-', user_id = v_user_id, layout = '[]', dashboard_filters_enabled = 'false'::boolean, is_archived = 'false'::boolean, is_draft = 'false'::boolean, tags = '{audit}'::varchar[], options = '{}'::json WHERE id = v_dashboard_132; END IF;
-- Replace widgets on upserted dashboards
        DELETE FROM widgets WHERE dashboard_id = v_dashboard_128;
        DELETE FROM widgets WHERE dashboard_id = v_dashboard_129;
        DELETE FROM widgets WHERE dashboard_id = v_dashboard_130;
        DELETE FROM widgets WHERE dashboard_id = v_dashboard_131;
        DELETE FROM widgets WHERE dashboard_id = v_dashboard_132;
-- Widgets
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 08:52:22.173573+00'::timestamptz, '2026-07-23 06:51:38.935676+00'::timestamptz, v_visualization_268, '', 1, '{"parameterMappings": {}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 2, "sizeY": 16, "minSizeX": 2, "maxSizeX": 6, "minSizeY": 1, "maxSizeY": 1000, "col": 0, "row": 0}}', v_dashboard_128) RETURNING id INTO v_widget_268;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 08:52:37.758805+00'::timestamptz, '2026-07-23 08:52:32.508341+00'::timestamptz, v_visualization_274, '', 1, '{"parameterMappings": {}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 4, "sizeY": 8, "minSizeX": 1, "maxSizeX": 6, "minSizeY": 5, "maxSizeY": 1000, "col": 2, "row": 0}}', v_dashboard_128) RETURNING id INTO v_widget_269;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 08:54:47.620273+00'::timestamptz, '2026-07-23 08:54:37.207524+00'::timestamptz, v_visualization_269, '', 1, '{"parameterMappings": {"event_date": {"name": "event_date", "type": "dashboard-level", "mapTo": "event_date", "value": null, "title": ""}, "limit": {"name": "limit", "type": "dashboard-level", "mapTo": "limit", "value": null, "title": ""}}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 6, "sizeY": 19, "minSizeX": 2, "maxSizeX": 6, "minSizeY": 1, "maxSizeY": 1000, "col": 0, "row": 0}}', v_dashboard_129) RETURNING id INTO v_widget_270;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 08:57:41.609353+00'::timestamptz, '2026-07-23 08:57:33.436025+00'::timestamptz, v_visualization_270, '', 1, '{"parameterMappings": {"request_id": {"name": "request_id", "type": "dashboard-level", "mapTo": "request_id", "value": null, "title": ""}, "event_date": {"name": "event_date", "type": "dashboard-level", "mapTo": "event_date", "value": null, "title": ""}}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 6, "sizeY": 14, "minSizeX": 2, "maxSizeX": 6, "minSizeY": 1, "maxSizeY": 1000, "col": 0, "row": 0}}', v_dashboard_130) RETURNING id INTO v_widget_271;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 09:01:34.961055+00'::timestamptz, '2026-07-23 09:01:10.520427+00'::timestamptz, v_visualization_271, '', 1, '{"parameterMappings": {"event_date": {"name": "event_date", "type": "dashboard-level", "mapTo": "event_date", "value": null, "title": ""}}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 3, "sizeY": 14, "minSizeX": 2, "maxSizeX": 6, "minSizeY": 1, "maxSizeY": 1000, "col": 0, "row": 0}}', v_dashboard_131) RETURNING id INTO v_widget_272;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 09:01:37.212773+00'::timestamptz, '2026-07-23 09:01:23.987102+00'::timestamptz, v_visualization_273, '', 1, '{"parameterMappings": {"event_date": {"name": "event_date", "type": "dashboard-level", "mapTo": "event_date", "value": null, "title": ""}}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 3, "sizeY": 14, "minSizeX": 1, "maxSizeX": 6, "minSizeY": 5, "maxSizeY": 1000, "col": 3, "row": 0}}', v_dashboard_131) RETURNING id INTO v_widget_273;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 09:04:07.381006+00'::timestamptz, '2026-07-23 09:03:57.325763+00'::timestamptz, v_visualization_272, '', 1, '{"parameterMappings": {"event_date": {"name": "event_date", "type": "dashboard-level", "mapTo": "event_date", "value": null, "title": ""}}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 3, "sizeY": 11, "minSizeX": 2, "maxSizeX": 6, "minSizeY": 1, "maxSizeY": 1000, "col": 0, "row": 0}}', v_dashboard_132) RETURNING id INTO v_widget_274;
        INSERT INTO widgets (updated_at, created_at, visualization_id, text, width, options, dashboard_id) VALUES ('2026-07-23 09:04:05.302374+00'::timestamptz, '2026-07-23 09:04:05.228825+00'::timestamptz, v_visualization_275, '', 1, '{"parameterMappings": {"event_date": {"name": "event_date", "type": "dashboard-level", "mapTo": "event_date", "value": null, "title": ""}}, "isHidden": false, "position": {"autoHeight": false, "sizeX": 3, "sizeY": 8, "minSizeX": 1, "maxSizeX": 6, "minSizeY": 5, "maxSizeY": 1000, "col": 3, "row": 0}}', v_dashboard_132) RETURNING id INTO v_widget_275;
-- Remap widget identifiers embedded in dashboard layouts
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '268' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_268::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_128;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '269' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_269::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_128;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '270' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_270::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_129;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '271' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_271::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_130;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '272' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_272::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_131;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '273' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_273::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_131;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '274' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_274::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_132;
        UPDATE dashboards SET layout = COALESCE((SELECT jsonb_agg(CASE WHEN jsonb_typeof(layout_item.value) = 'object' AND layout_item.value ->> 'i' = '275' THEN jsonb_set(layout_item.value, '{i}', to_jsonb(v_widget_275::text)) ELSE layout_item.value END) FROM jsonb_array_elements(layout::jsonb) AS layout_item(value)), '[]'::jsonb)::text WHERE id = v_dashboard_132;
    END
$redash_migration_5da377a970624ae4caa844c17c4b69a0$;