{{- if and .Values.networkPolicy .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trino.fullname" . }}-allow-redash
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  # 1. Дозвіл Trino звертатися до самого себе (Self-communication / Discovery)
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Chart.Name }}
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 8080

  # 2. Дозвіл для redash-admin
  - from:
    - podSelector:
        matchLabels:
          app: redash-admin
    ports:
    - protocol: TCP
      port: 8080

  # 3. Дозвіл для redash-viewer
  - from:
    - podSelector:
        matchLabels:
          app: redash-viewer
    ports:
    - protocol: TCP
      port: 8080
{{- end }}
