{{- if and .Values.networkPolicy .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trino.fullname" . }}-allow-redash
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
    from:
    # 1. Дозвіл Trino звертатися до самого себе (Self-communication / Discovery)
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Chart.Name }}
          app.kubernetes.io/instance: {{ .Release.Name }}
    # 2. Дозвіл для redash-admin
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redash-admin
    # 3. Дозвіл для redash-viewer
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redash-viewer
{{- end }}
